#!/bin/sh

#build mc spigot server
curl -z BuildTools.jar -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
java -jar BuildTools.jar --rev latest
cp ./spigot*.jar ./server.jar

#create eula.txt
cat <<EOF > ./eula.txt
# Generated by docker build 
eula=true
EOF
